// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CalcTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void calc() {
    driver.get("http://localhost:8181/");
    driver.manage().window().setSize(new Dimension(1322, 816));
    driver.findElement(By.linkText("Calculadora")).click();
    {
      String value = driver.findElement(By.id("txtPantalla")).getAttribute("value");
      assertThat(value, is("0"));
    }
    driver.findElement(By.cssSelector(".btnDigito:nth-child(8)")).click();
    {
      String value = driver.findElement(By.id("txtPantalla")).getAttribute("value");
      assertThat(value, is("9"));
    }
    driver.findElement(By.cssSelector(".btnOperar:nth-child(5)")).click();
    {
      String value = driver.findElement(By.id("txtResumen")).getAttribute("value");
      assertThat(value, is("9 +"));
    }
    driver.findElement(By.cssSelector(".btnDigito:nth-child(14)")).click();
    driver.findElement(By.cssSelector(".btnOperar:nth-child(21)")).click();
    {
      String value = driver.findElement(By.cssSelector(".btnOperar:nth-child(21)")).getAttribute("value");
      assertThat(value, is("="));
    }
    driver.findElement(By.cssSelector(".btnOperar:nth-child(9)")).click();
    {
      String value = driver.findElement(By.id("txtResumen")).getAttribute("value");
      assertThat(value, is("10 -"));
    }
    driver.findElement(By.cssSelector(".btnDigito:nth-child(12)")).click();
    driver.findElement(By.cssSelector(".btnOperar:nth-child(21)")).click();
    {
      String value = driver.findElement(By.id("txtPantalla")).getAttribute("value");
      assertThat(value, is("4"));
    }
    driver.findElement(By.cssSelector(".btnOperar:nth-child(13)")).click();
    driver.findElement(By.cssSelector(".btnDigito:nth-child(6)")).click();
    {
      String value = driver.findElement(By.cssSelector(".btnDigito:nth-child(6)")).getAttribute("value");
      assertThat(value, is("7"));
    }
    driver.findElement(By.cssSelector(".btnOperar:nth-child(21)")).click();
    {
      String value = driver.findElement(By.id("txtPantalla")).getAttribute("value");
      assertThat(value, is("28"));
    }
    driver.findElement(By.cssSelector(".btnOperar:nth-child(17)")).click();
    driver.findElement(By.cssSelector(".btnDigito:nth-child(16)")).click();
    driver.findElement(By.cssSelector(".btnDigito:nth-child(20)")).click();
    driver.findElement(By.cssSelector(".btnDigito:nth-child(11)")).click();
    driver.findElement(By.cssSelector(".btnOperar:nth-child(21)")).click();
    {
      String value = driver.findElement(By.id("txtPantalla")).getAttribute("value");
      assertThat(value, is("8"));
    }
    driver.findElement(By.cssSelector(".btnOperar:nth-child(13)")).click();
    driver.findElement(By.cssSelector(".btnDigito:nth-child(19)")).click();
    driver.findElement(By.cssSelector(".btnOperar:nth-child(21)")).click();
    driver.findElement(By.cssSelector(".btnOperar:nth-child(17)")).click();
    driver.findElement(By.cssSelector(".btnDigito:nth-child(14)")).click();
    driver.findElement(By.id("btnIniciar")).click();
    driver.findElement(By.cssSelector(".btnOperar:nth-child(17)")).click();
    driver.findElement(By.cssSelector(".btnDigito:nth-child(19)")).click();
    driver.findElement(By.cssSelector(".btnOperar:nth-child(21)")).click();
    {
      String value = driver.findElement(By.id("txtPantalla")).getAttribute("value");
      assertThat(value, is("NaN"));
    }
  }
}
